### ISSUE TITLE
Add_new_style_login

### ISSUE THREAD

**Issue by Web-ski** [tgbdc7/zeton#102]
Stworzenie nowego brancha: 96/add_new_style_login
Zmiana:
- kodu login.html (jako witryny pierwszego dostępu)
Dodanie: 
- struktury plików sass (pliki style.scss, _variables.scss, _normalize.scss oraz głównych komponentów i sekcji: _login.scss i _login-header.scss)
- pliku style.css i style.css.map jako źródła nowego layoutu
- ostylowanie pliku login.html

**Comment by tgbdc7** [comment]
done
