### ISSUE TITLE
Add_npm_and_gulp_files_for_sass_compilation

### ISSUE THREAD

**Issue by Web-ski** [tgbdc7/zeton#106]
Stworzenie nowego brancha 98/add_npm_and_gulp_files_for_sass_compilation
Zawierającego środowisko npm i gulp oraz kod do kompilacji kodu sass/scss na css.
UWAGA, poszczególne programy zawarte w gulpfile.js wymagają instalacji w środowisku lokalnym.

**Comment by tgbdc7** [comment]
done
