### ISSUE TITLE
odejmowanie liczby ujemnej  

### ISSUE THREAD

**Issue by zakonfeniksa** [tgbdc7/zeton#11]
jak sie spróbuje odjac liczbe ujemna to sie doda

**Comment by gruszal** [comment]
To jest bug, Czy feature do dodawania? Musisz opisać bardziej szczegółowo.

**Comment by tgbdc7** [comment]
To jest bug w wersji 0.1 (tej która jest odpalona na serwerze www.zeton.usermd.net ) - przy wykorzystaniu punktów można wpisać ujemną liczbę   co powoduje dodanie punktów :). Zgłoszone aby uniknąć tego w następnych wersjach.

**Comment by pokojskamartyna** [comment]
poprawilam to w funkcji, ktora odejmuje punkty
