### ISSUE TITLE
caregiver can edit prizes

### ISSUE THREAD

**Issue by visse0001** [tgbdc7/zeton#125]
Opiekun może usuwać istniejące nagrody, dodawać nowe, edytować istniejące

**Comment by bizmarcin** [comment]
Moim zdaniem funkcjonalnie powinno być tak że w momencie kiedy chcemy edytować daną nagrodę powinniśmy klikać na przycisk z poziomu menu nagród i dostawać wypełniony formularz aktualnymi danymi tak żeby aktualizować tylko i wyłącznie dane które nas interesują. Może być to lista rozwijana przeniesiona o piętro wyżej lub przycisk edytuj dla każdej z nagród.
