### ISSUE TITLE
Rozdzielenie użytkowników na różne "rodzaje"

### ISSUE THREAD

**Issue by gruszal** [tgbdc7/zeton#13]
Definition of done:
- wprowadzenie rozróżnienia użytkowników ze względu na ich role i uprawnienia
- w zależności od tego jaki użytkownik się zaloguje, na stronie głównej ma być to odnotowane:
  - *dziecko* widzi swojego *opiekuna*
  - *opiekun* widzi listę wszystkich swoich *dzieci*
- stworzenie zestawów użytkowników do testów

Mam pytanie odnośnie nomenklatury: używamy *dziecko* i *opiekun*?

**Comment by tgbdc7** [comment]
Póki co nic lepszego nie nie wymyśliłem niż: dziecko i opiekun, więc tak bym zostawił. Chyba, że ktoś ma lepszy pomysł ? 

P.S Ostatnio pokazywałem obecną wersję znajomej. Powiedziała: "Ekstra pomysł, muszę taki system zrobić mężowi". Także ... kto wie co przyniesie przyszłość.

**Comment by gruszal** [comment]
W kodzie używam "child" i "caregiver". Wydaje mi się, że jest to najkorzystniejsze tłumaczenie.
