### ISSUE TITLE
Ekran logowania

### ISSUE THREAD

**Issue by gruszal** [tgbdc7/zeton#14]
Ekran logowania jest fatalny :)
Trzeba go zrobić zupełnie od początku, kto się podejmie?

Minimalne wymagania:
- pole "login" i "hasło" podpisane
- wyświetlona nazwa aplikacji
- jakakolwiek szata graficzna (na razie nie ma nic)

**Comment by tgbdc7** [comment]
Czy już ktoś się zgłosił :) ?

**Comment by gruszal** [comment]
Jest twój :) Polecam przy jego tworzeniu wykorzystać już bootstrapa.

**Comment by tgbdc7** [comment]
Bardziej myślałem, żeby dodać do zespołu speca od front-endu :)
