### ISSUE TITLE
nowy wygląd strony index_caregiver.html

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#23]
Przerobienie frontu strony tak aby była zgodna z szatą graficzną strony logowania.

**Comment by HannnaK** [comment]
zajmę się

**Comment by Web-ski** [comment]
Ja też się za to wezmę.

**Comment by tgbdc7** [comment]
Wersja podstawowa tego zadania została wykonana. Zamykam ten issue. @Web-ski zostanie dodany nowy issue na "dopieszczenie" wyglądu. Liczymy na Ciebie ;)
