### ISSUE TITLE
nowy wygląd strony child_info 

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#24]
Zmienić kolory zgodnie z tym jak na stronie logowania. 
Podział na 4 bloki ma nadal być zachowany.  
Bootstrap ma działać poprawnie ;)

**Comment by HannnaK** [comment]
zajmę się

**Comment by Web-ski** [comment]
Ja też się za to wezmę.

**Comment by tgbdc7** [comment]
Wersja podstawowa tego zadania została wykonana. Zamykam ten issue. @Web-ski zostanie dodany nowy issue na "dopieszczenie" wyglądu. Liczymy na Ciebie ;)
