### ISSUE TITLE
Zmiana funkcjonalności warnów i banów 

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#26]
Zmiana funkcjonanalności **KONSEKWENCJI**: ( banów, warnów, kicków)

**Stosujemy stopniowanie konsekwencji:**  poprzez wskażnik o odpowiednim nr (id_ban) . 
1. WARN - ostrzeżenie (nazwa czynności/konsewkencji zależna od dziecka)
2. WARN - ostrzeżenie (nazwa czynności/konsewkencji zależna od dziecka)
3. WARN - KICK (nazwa czynności/konsewkencji zależna od dziecka)
4. WARN - BAN 2 stopnia tymczasowy na 30 minut. (nazwa czynności/konsewkencji zależna od dziecka)
5. WARN - BAN 1 stopnia na 24h (nazwa czynności/konsewkencji zależna od dziecka)
6 WARN - BAN 2 stopnia na 24h(nazwa czynności/konsewkencji zależna od dziecka)

**Mamy 3 przyciski:**
1. DAJ WARN'a
2. DAJ KICK'a
3. DAJ BAN'a

AD1. WARN przekakuje po kolei od 1 do 6. W momenci gdy osiągnie odpowiedni poziom jest realizowane to co w nawiasie. Na którym poziomie warna ostrzeżenia jesteśmy możemy informować np innym kolorem czcionki. 
AD2. KICK - od razu ustawia wskaźnik konsekwencji na poziomie 3. 
AD3 BAN - ustawia wskaźnik konsekwencji na poziomie 6. 

**Zasady:**
1.można dać kick bez warna
2.można dać bana bez warna 
3.kick i ban daje się automatycznie gdy wskażnik konsekwencji przejdzie przez odpowiednie poziomy. 3 i 6 
4. Warny - restują się po pólnocy - nastepny dzień.
5. Ban restuje się po skończeniu czasu: stop_time.
6. Danie bana w momencie gdy jest już ban powoduje wydłużenie czasu bana o 24h - do stop_time dodajemy 24h ( 10 minut w wersji testowej) 

**Defincja of done:**
- [x] zmiana struktury bazy dancyh dwie tabelki bans oraz bans_name
- [x] w tabeli "bans" - mamy następujące kolumny: id, id_child (foregin), id_ban (liczba_od 1 do 6), start_time, stop_time
- [x] w tabeli "bans_name"- mamy nastepujące kolumny: id, id_child(foregin), id_ban, ban_name (nazwa konsekwencji zależna od dziecka) 
- [x] dodanie przycisku "daj WARN'a" - oraz jego obsługa 
- [x] dodanie przyskiu "daj KICK'a" - oraz jego obsługa
- [x] dodanie przycisku "daj BAN'a" - oraz jego obsługa
- [x]  zmiana koloru czcionki zależna od wskażnika konsekwencji 
- [x] automatyczne kasowanie warnów (oprócz 6 stopnia) po północy
- [x] automatyczne kasowanie bana (6 stopień konsekwencji) po upływie czasu stop_time
- [x] Danie kolejnego bana powoduje wydłużenie czasu o 24h
- [x] Danie kolejnego kicka gdy wskażnik konsekwencji jest na poziomie 3 lub większy - nie powoduje nic ( w poźniejszej wersji przycisk powinien być nieaktywny - szary)
- [x] Zmiana sposobu odczytu banów na stronie index_caregiver
- [x]  Zmiana w tabelce "bans" odbywa się poprzez modyfikację (update) - nie przez dodanie kolejnego wpisu

Trochę tego wyszło - jesli są pytania zapraszam.

**Comment by tgbdc7** [comment]
obecnie będę nad tym pracować ;)

**Comment by zakonfeniksa** [comment]
W child_info.html w 10 linijce nie powinno być <html> bo taki element już jest w linijce drugiej

**Comment by tgbdc7** [comment]
poprawiłem, dobra czujność @zakonfeniksa  ;)
