### ISSUE TITLE
Lista punktów do zdobycia inna dla każdego dziecka

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#27]
modyfikacja bazy dancyh tak aby każde dziecko miało osbną listę możliwość zdobywania punktów. Osbna tabela "home_points" - - maksymalnie 10 wpisów na dziecko 
**Definition of Done:**
- [ ] Nowa tabela "home_points": 
- id
- id_child(foregin keys)
- name(nazwa czynnosći)
- value(ilość punktów)
- order_list(przydatne do kolejności wypisywania - aktualnie możemy stosować im mniej punktów tym wyżej na liście, w przyszłości może być to wykorzytanie inaczej)
- max_day
- max_week 
- [ ] wypisywanie na stornie child_info listę punktów do zdobycia z bazy dla konkretnego dziecka

**Comment by visse0001** [comment]
Zrobię to :)

**Comment by visse0001** [comment]
Zamiast 'value' (pycharm mi go podkreślał, chyba czytał jako treść sql'ową) użyłam słowa 'points'. Może tak zostać? Tak samo zrobię w przypadku #28

**Comment by tgbdc7** [comment]
Myślę że może być points. :)
