### ISSUE TITLE
Lista nagród do wykorzystania inna dla każdego dziecka

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#28]
Nowa tabelka "prizes" 
ma następujące kolumny:

- id
- id_child (foregin keys)
- name
- value (ilość punktów)
- order_list (kolejność do wyświetlania - obecnie możemy stosować że najmnijesza wartość punktów jest wyświeltana u góry)
- max_day ( ile danej nagordy możemy wykorzystać w ciagy 24h) - jeśli pole puste to bez ograniczeń 
- max_week (ile danej nagrody możemy wykorzystać na tydzień)- jeśli pole puste to bez ograniczeń 
- max_month (ile danej nagrody możemy wykorzystać na w miesiąc) - jeśli pole puste to bez ograniczeń 

**Definition of Done:**

- [ ]  zmiana struktury bazy dancyh - dodanie tabeli "prizes"
- [ ]  wyswietlanie nagród z bazy dancyh

**Comment by visse0001** [comment]
Zrobię to
