### ISSUE TITLE
dodanie strony Ustawienia 

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#31]
Link do strony dostepny po zalagowaniu. 

- [ ] Wypisanie informacji o użytkowniku (narazie jest tylko imię )

- [ ] Możliwość zmiany hasła (trzeba podać aktualne hasło) 

- [ ] Nowe haslo ma być zapisane w bazie w postaci zahasowanej

**Comment by visse0001** [comment]
Zrobię to
