### ISSUE TITLE
Dodanie pola email - do użytkownika.

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#32]
**Defintion of done**

- [x] wyświetlenie informacji o adresie na stronie: ustawienia
- [x] zmiana struktury bazy danych tabeli users: dodanie pola email

**Comment by pokojskamartyna** [comment]
zajmę się tym i resetem :)

**Comment by tgbdc7** [comment]
@pokojskamartyna jak idzie? Przydzielić kogoś do pomocy przy tym issue?

**Comment by tgbdc7** [comment]
done
