### ISSUE TITLE
Dodanie rejestracji nowych użytkowników 

### ISSUE THREAD

**Issue by pokojskamartyna** [tgbdc7/zeton#39]

**Comment by janiszewskibartlomiej** [comment]
Czy to zadanie jest zrobione czy mogę zrobić? Jakie są wymagania?

**Comment by tgbdc7** [comment]
Patryk to robi jest w trakcie. MAsz z prawej strony osoby przydzielone do danego zadania `Assignees` - można siebie przydzielać. To zadanie wbrew pozorom nie jest łatwe. Propponuje na pierwszy ogień jakieś prostrze, żeby poznać projekt. Z etykietką `good first issue` np zmiana imienia #69

**Comment by janiszewskibartlomiej** [comment]
Dziękuję, zastosuje się 😃

Z wyrazami Szacunku

Bartłomiej Janiszewski
T: 533444999
