### ISSUE TITLE
dodanie testu/testów aplikacji 

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#43]
Aplikacja się rozrasta. Potrzebujemy testów. 
Aby zachęcić proponuję prosty issue: 
Defintion Of Done:

- [ ] dodanie jednego testu

**Comment by visse0001** [comment]
Nie znam się na tym, ale spróbuję się wgryźć w temat.

**Comment by gruszal** [comment]
Tutaj jest modelowy przykład: https://github.com/pallets/flask/tree/1.0.2/examples/tutorial

**Comment by tgbdc7** [comment]
pierwsze testy zostały wdrożone:)
