### ISSUE TITLE
Poprawienie templatki - estetyki pliku child_info.html oraz index_child.html

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#44]
minimalne wymaganie: poprawienie pola formularza przy dodawaniu punktów i wykrozystawaniu punktów tak aby nie zajmował całej szerokości diva, wówczas gdy korzystamy z przeglądarki na komputerze. 
Wszelkie inne poprawki mile widziane.
Defintion Of Done:

- [ ] pole formularza "wykorzystaj punkty" oraz "dodaj punkty" w pliku "child_info.htlm" nie zjamuje całej szerkości diva w momencie gdy korzystamy z przeglądarki na komputerze.
- [ ] pole formularza "wykorzystaj_punkty" w pliku "index_child.html" nie zjamuje całej szerkości diva w momencie gdy korzystamy z przeglądarki na komputerze.
- [ ] odpowiednia szerokosć pola formularza w moemncie gdy korzystamy z wersji mobilnej

**Comment by visse0001** [comment]
Proponuję zamienić:
caregiver_panel.html -> słowo "dodawaj" na "dodaj"
index_child.html -> słowo "sposób" na "sposoby", słowo "NAGRODY" na "Nagrody"

**Comment by tgbdc7** [comment]
wprowadzamy nowe style - ten issue nieaktulany
