### ISSUE TITLE
wyświetlania historii punktów w widoku `task_detail`

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#62]
Wyświetlenie historii ostatnich **10** zdarzeń na punktach w widoku szczegółowym `task_detail`
- [x] w widoku szczegółowym dla danego child_id wyświetlania historii ostatnich 10 zdarzeń na punktach
- [x]  jeśli nie ma tylu zdarzeń to wyświetlamy taką ilość jaka jest
- [x] wyświetlamy informację z tabeli `points_history` 
- [x] wyświetlamy: liczbę punktów która się zmieniła, kto zmienił `username` oraz datę zmiany 
- [x] wersji na komputer informację umieszczamy obok szczegółu punktów
- [x]  strona ma nadal być responsywana. w wersji na male ekrany informacja o historii ma przejść poniżej informacji o punktach
- [x] dodać przycisk `wróć` - który został pominięty przy tworzeniu widoku szczegółowego

**Comment by visse0001** [comment]
Co to znaczy:
"wersji na komputer informację umieszczamy obok szczegółu punktów" ?
Mamy stworzyć wersję na komputer i wersje mobilną?

**Comment by tgbdc7** [comment]
Żeby przy małym ekranie czyli w wersji mobilnej - historia wyświetlała się pod spodem zamiast z boku. Generalnie żeby strona była responsywna.

**Comment by visse0001** [comment]
Nie ogarniam responsywności w html, ale postaram się to zrobić.

**Comment by tgbdc7** [comment]
Można zgapić classy bootstrapowe z child_info

**Comment by tgbdc7** [comment]
done
