### ISSUE TITLE
modyfikacja api/bans

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#65]
Zmodyfikowanie api bans w ten sposób, aby po wywołaniu funkcji `give_kick`, `give_ban`, `give_warn` powróciło na stronę z której funkcja została wywołana. 
- [ ] poprawne działanie dla zalogowanego opiekuna
- [ ] poprawne działanie dla zalogowanego dziecka
- [ ] Dodanie przycisków `daj warna`, `daj kicka`, `daj bana` w widoku szczegółowym

**Comment by gruszal** [comment]
Z tym wiąże się jeszcze jedna sprawa. Mianowicie, trzy funkcje w `api/bans.py` są praktycznie identyczne, różnią się tylko wywołaniem jednej z trzech funkcji z `data_access/bans.py`. Proponuję ściągnąć to wszystko do jednego endpointu, ale nie wiem jak powinien się nazywać. 
Czy warn/kick/ban to trzy poziomy _czegoś_? Jeśli tak, to jak to coś się nazywa?

**Comment by tgbdc7** [comment]
to 3 poziomy konsekwencji.

**Comment by gruszal** [comment]
czy możemy te trzy poziomy konsekwencji nazwać jednym terminem?

**Comment by tgbdc7** [comment]
Tak, jak najbardziej możemy. Szukam odpowiedniego słowa. Tak jak już mówiłem testuję rozwiązanie z warnami/banami/kickami. Próbuje połączyć dwa światy :). Zauważyłem, że konsekwencje sprawiają największy problem ze zrozumieniem, bo nie są intuicyjne. Muśmy to uprościć. Z punktu widzenia psychologicznego powinny nazywać się `konsekwencje`. Ale z punktu widzenie dziecka powinny nazywać się tak żeby dziekco zrozumiało. Natomiast z punktu widzenia programisty to tylko api, które nie jest w jawny sposób przekazywane do użytownika, więc zamiast 
`consequence` proponuje dać `api/warn`, a jeszcze lepiej `api/ban`. Mamy w projekcie plik bans.py, mamy też tabele w bazie bans oraz bans_name więc będzie wszystko powiązane :).  Jak uważacie?
