### ISSUE TITLE
kontrola `max_day`

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#80]
W nawiązaniu do zadania:
https://github.com/tgbdc7/zeton/issues/79#issue-494237153
Dodać do każdego przycisku sprawdzenie czy możemy zdobyć punkty za dane zadanie. Sprawdzamy poprzez tabelę `points_history`. W momencie gdy nie możemy wykorzystać danej nagrody musimy dać znać poprzez flash message. 

UWAGA tutaj sprawdzamy jedynie czy nie przekraczymy ilości zawartej w `max_day` w tabeli `home_points`

**Comment by tgbdc7** [comment]
@bizmarcin jak idzie z tym zadaniem?

**Comment by bizmarcin** [comment]
Dziś powinienem założyć PR.
