### ISSUE TITLE
dodanie kolumny `is_active` do tabeli `home_points` 

### ISSUE THREAD

**Issue by tgbdc7** [tgbdc7/zeton#83]
Obecnie zbieramy wszystkie zadania z tabeli `home_points`. Musimy stworzyć osobną kolumną w tabeli, która pozowli nam stwierdzić czy dane zadanie jest jeszcze możliwe do wykonania. 
Defintion of done:

- [x] dodanie kolumny `is_active` do tabeli `home_points`
- [x] dopuszczalne wartości w tej kolumnie to `0` lub `1` 
- [x] wyświetlanie zadania w sekcji `dodanie_punktów` w momencie gdy zadanie jest aktywne 
- [x] ta sama funkcjonalność musi być dostepna w widoku ogólnym jak i szczegółowym
- [x] modyfikacja danych startowych

**Comment by bizmarcin** [comment]
moje rozwiązanie w branch: 83_add_active_col_table_is_active

**Comment by tgbdc7** [comment]
Wystaw pull requesta :)

**Comment by bizmarcin** [comment]
To już chyba poszło do mastera...

**Comment by tgbdc7** [comment]
done
